name: Snyk example 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master        
    - name: Output Snyk code test
      run: |
       snyk auth
       snyk code test --json-file-output=vuln.json 
    - name: upload test result
      run: |
       echo hello > path/to/artifact/world.txt
       mkdir -p path/to/artifact
      run: 
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
      
      continue-on-error: true

    ##- name: Snyk Open Source monitor
      ##run: snyk monitor --all-projects

      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
