name: Snyk example 
on: push
jobs: 
  name: security
  runs-on: ubuntu-latest    
  steps:
    env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master        
    - name: Output Snyk code test
    env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      run: |
       snyk auth
       snyk code test --json-file-output=vuln.json 
    - name: make directory
      run: |
       echo hello > path/to/artifact/world.txt
       mkdir -p path/to/artifact
    
    - name: upload      
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
      
      continue-on-error: true

    ##- name: Snyk Open Source monitor
      ##run: snyk monitor --all-projects

      