name: Snyk example 
on: push
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - name: ignore certain files
      run: snyk ignore --file-path=performance && snyk ignore --file-path=troubles
      
        
    - name: Output Snyk code test
      run:  snyk code test --json-file-output=path/to/artifact/vex.json
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: upload
      run: |
        mkdir -p path/to/artifact
        echo hello > path/to/artifact/world.txt

    - name: execute upload with
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          path/to/artifact/vex.json
          home/runner/work
         