name: Snyk example 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
        
    - name: Output Snyk code test
      run: snyk code test 
      continue-on-error: true
    - name: Output Snyk code test
      run: actions/upload-artifact@v3
        with:
          name: SAST-file
          path: |
          test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
