name: Snyk example 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
        
    - name: Output Snyk code test
      run: snyk auth
      run:  snyk code test --json-file-output=vuln.json 
    - name: upload test result
      uses:
      continue-on-error: true

    - name: Snyk Open Source monitor
      run: snyk monitor --all-projects

      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
